### ISSUE TITLE
query params of deep links are not working outside of tinlake

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-ui#293]
for loan issue:
https://kovan.staging.tinlake.centrifuge.io/loans/issue/?tokenId=76248159083469891748948192629442814843543974800057095916516138115057567075341&registry=0xac0c1ef395290288028a0a9fdfc8fdebebe54a24
for loan details: 
https://staging.tinlake.centrifuge.io/loans/loan/?loanId=3
for investor details:
https://staging.tinlake.centrifuge.io/investments/investor/?investorAddress=0x790c2c860DDC993f3da92B19cB440cF8338C59a6

**Comment by philipstanislaus** [comment]
This is caused by https://github.com/zeit/next.js/issues/5214 (next.js does not support trailing slashes), but Netlify adds them.

From Netlify's docs: 

> You cannot use a redirect rule to add or remove a trailing slash

Source: https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash)

I did implement a workaround on the client side, inspired by some comments in https://github.com/zeit/next.js/issues/5214 : https://github.com/centrifuge/tinlake-ui/pull/299

**Comment by philipstanislaus** [comment]
The above is fixing the issue locally, but not on Netlify. It seems there is something else wrong with redirects, need to investigate further.
