### ISSUE TITLE
Regression: fix numberInputFields Layout 

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-ui#315]
- After package upgrades NumberInputFields Layout is broken. The components have borders. Padding is also wrong

**Comment by philipstanislaus** [comment]
This is caused by the upgrade from grommet 2.7.5 to 2.13.0. 

I upgraded grommet in the axis repository and fixed the issue there: https://github.com/centrifuge/axis/pull/56

## Screenshots

### grommet 2.7.5 
<img width="823" alt="Bildschirmfoto 2020-05-16 um 12 43 13" src="https://user-images.githubusercontent.com/6912756/82117955-26bad380-9774-11ea-80aa-ed0c0f5b6c5f.png">

### grommet 2.13.0, without fix
<img width="820" alt="Bildschirmfoto 2020-05-16 um 12 43 47" src="https://user-images.githubusercontent.com/6912756/82117958-2f130e80-9774-11ea-87d8-5fbd5c2b8eda.png">


### grommet 2.13.0, with fix
<img width="821" alt="Bildschirmfoto 2020-05-16 um 12 44 01" src="https://user-images.githubusercontent.com/6912756/82117962-35a18600-9774-11ea-9587-d3348b3b2d4b.png">
